services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../images:/app/images
    restart: unless-stopped
    container_name: random-image-api
